export const GET_DOCTORS='GET_DOCTORS'
export const SET_LOADING='SET_LOADING'
export const VIEW_DOCTOR='VIEW_DOCTOR'

export const OPEN_APPOIMENT_MODAL='OPEN_APPOIMENT_MODAL'
export const CLOSE_APPOIMENT_MODAL='CLOSE_APPOIMENT_MODAL'

export const CHANGE_VALUE='CHANGE_VALUE'

export const SUCCESS_SUBMIT_APPOIMENT='SUCCESS_SUBMIT_APPOIMENT'
export const FAILED_SUBMIT_APPOIMENT='FAILED_SUBMIT_APPOIMENT'
export const SUBMIT_LOADING='SUBMIT_LOADING'
export const SEARCH_KEYWORD_DOCTOR='SEARCH_KEYWORD_DOCTOR'
export const SEARCH_DOCTOR='SEARCH_DOCTOR'